services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network

  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - mssql

  todo-client:
    build:
      context: ./src/todos-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network
    depends_on:
      - todo-api

volumes:
  mssql_data:

networks:
  app_network:
    driver: bridge